AppQuality/unguess-design-system

package.json
src/index.tsx
src/stories/buttons/anchor/index.stories.tsx
src/stories/buttons/button/index.stories.tsx
src/stories/typography/block-quote/_types.tsx
src/stories/typography/block-quote/index.stories.tsx
src/stories/typography/block-quote/index.tsx
src/stories/typography/code/_types.tsx
src/stories/typography/code/index.stories.tsx
src/stories/typography/code/index.tsx
src/stories/typography/ellipsis/_types.tsx
src/stories/typography/ellipsis/index.stories.tsx
src/stories/typography/ellipsis/index.tsx
src/stories/typography/lists/_types.tsx
src/stories/typography/lists/index.tsx
src/stories/typography/lists/ordered.stories.tsx
src/stories/typography/lists/unordered.stories.tsx
src/stories/typography/paragraph/_types.tsx
src/stories/typography/paragraph/index.tsx
src/stories/typography/paragraph/ordered.stories.tsx
src/stories/typography/typescale/_types.tsx
src/stories/typography/typescale/index.stories.tsx
src/stories/typography/typescale/index.tsx
yarn.lock

Add: blockQuote, code, ellipsis, lists, paragraph, typescale

Typography components

---

src/stories/table/index.tsx

…to pass all available props and not only children

fix(table): changed types definition for extras elements

---

src/stories/dropdowns/menu/index.stories.tsx
src/stories/shared/globalStyle.ts

<details>
<summary>📦 Published PR as canary version: <code>2.8.28--canary.41.1d4c57d.0</code></summary>
<br />
:sparkles: Test out this PR locally via:
```bash
npm install @appquality/unguess-design-system@2.8.28--canary.41.1d4c57d.0
yarn add @appquality/unguess-design-system@2.8.28--canary.41.1d4c57d.0
```
</details>

Cup 627 new scrollbar design

---

package.json
src/stories/charts/ChartContainer.tsx
src/stories/charts/bar/_types.ts
src/stories/charts/bar/index.stories.tsx
src/stories/charts/bar/index.tsx
src/stories/charts/line/_types.ts
src/stories/charts/line/index.stories.tsx
src/stories/charts/line/index.tsx
src/stories/charts/pie/_types.ts
src/stories/charts/pie/index.stories.tsx
src/stories/charts/pie/index.tsx
src/stories/charts/stream/_types.ts
src/stories/charts/stream/index.stories.tsx
src/stories/charts/stream/index.tsx
yarn.lock

line chart and wrapper interface

[UN-32] Line chart and wrapper interface

---

src/index.tsx

fix(tabs): export component

---

src/stories/charts/sunburst/index.stories.tsx
src/stories/charts/sunburst/index.tsx

- Remove math floor random item value percentage

fix(sunburst): remove tot state math random

---

src/stories/tags/_types.tsx
src/stories/tags/index.stories.tsx
src/stories/tags/index.tsx

Defaults: isPill and grey color and background
Color prop: change the text color and can override the white/black switch, which is the default right now

feat(Tag): add color prop and some default style

---

src/stories/navigation/page-header/index.stories.tsx
src/stories/navigation/page-header/index.tsx
src/stories/navigation/page-header/styled/main.tsx

- remove page header side padding to fit in app layout wrapper container

Un 532 page layout

---

src/stories/dropdowns/select/index.tsx
src/stories/multiselect/_types.tsx
src/stories/multiselect/index.tsx
src/stories/profile-modal/index.stories.tsx
src/stories/profile-modal/userMenu.tsx

**Tag**
- Add color props to handle text color
- Set default colors for hue (background) and color props
- Update story
**Page Header**
- Remove side padding
-  Update story

Tag colors & Page Header layout

---

src/stories/campaign-cards/index.tsx
src/stories/service-cards/index.tsx

service card and campaign card tags in bold and fix ellipsis

Fix-cards-tags

---

src/stories/navigation/page-header/_types.tsx
src/stories/navigation/page-header/index.stories.tsx
src/stories/navigation/page-header/index.tsx
src/stories/navigation/page-header/styled/main.tsx

**Page Header**
Optimized page header with new specifications:
- New spacings for all the sub-components
- New stories for all pages levels

Un 524 page header

---

src/stories/navigation/app-header/index.tsx

Fix:
- If not specified in the style prop, set zIndex front as default

fix(app-header): add zIndex front to prevent issues

---

package.json
src/stories/table/grouped.tsx
yarn.lock

🎨 style(grouped.tsx): remove react-spring animation and use CSS transform instead

🔥 chore(package.json): remove react-spring dependency

---

src/stories/navigation/nav/nav-item/navToggle.tsx

Fix: 
- Sidebar Icon position fixed.

Fix(SideBar): Sidebar Icon positioning

---

package.json
rollup.config.js
src/stories/forms/input-toggle/index.tsx

- Keep svg dimensions
- disable svgo plugin

Update rollup configuration

---

src/stories/color-swatch/index.stories.tsx
src/stories/color-swatch/index.tsx

🔀 chore(color-swatch): update export statement for ColorSwatch component

🔀 chore(color-swatch): update import statement for ColorSwatch component

---

src/stories/color-swatch/index.tsx

🐛 fix(color-swatch): fix color assignment bug in handleSelect function

🐛 fix(color-swatch): fix color selection bug in handleSelect function

---

src/stories/chat/parts/comment.tsx
src/stories/chat/parts/containers.tsx
src/stories/shared/editorStyle.tsx

🐛 fix(comment.tsx): set editable option to false for the editor
🎨 style(containers.tsx): remove unnecessary padding property
🎨 style(editorStyle.tsx): update readOnlyStyle to make it more consistent

🎨 style(comment.tsx): update ReadOnly style to make it more readable

---

src/stories/chat/_types.tsx
src/stories/chat/index.stories.tsx
src/stories/chat/parts/mentionList.tsx

✨ feat(chat): add support for i18n in mentionList.tsx
🔧 fix(chat): fix typo in index.stories.tsx
✨ feat(chat): add support for i18n in index.stories.tsx
🔧 fix(chat): fix import in _types.tsx
✨ feat(chat): add support for i18n in _types.tsx

🔧 fix(chat): fix typo in mentionList.tsx

---

src/stories/chat/index.stories.tsx
src/stories/chat/parts/containers.tsx

🐛 fix(containers.tsx): remove duplicate styles for .ProseMirror

🐛 fix(chat): remove unnecessary text in chat message

---

src/stories/player/parts/audioButton.tsx
src/stories/player/parts/container.tsx
src/stories/player/parts/controlButton.tsx
src/stories/player/parts/controls.tsx
src/stories/player/parts/controlsCenterGroup.tsx
src/stories/player/parts/floatingControls.tsx
src/stories/player/parts/fullScreenButton.tsx
src/stories/player/parts/timeLabel.tsx

This pull request includes updates to the player controls and refactors the styling of the controls. The changes include:
- Updated the player controls to use the `useVideoContext` hook from the `@appquality/stream-player` package.
- Refactored the styling of the controls to use styled components.
- Replaced the `IconButton` component with a new `ControlButton` component.
- Updated the background color of the player container to use the `theme.palette.grey[100]` color.
- Added a new `Cutter` button to the controls.
- Updated the styling of the `FloatingControls` component to include a box shadow.
- Updated the styling of the `FullScreenButton` component to use the `ControlButton` component and the `theme.palette.grey[700]` color.
- Updated the styling of the `TimeLabel` component to use …

"Update player controls and refactor styling"

---

src/stories/highlight/index.tsx

🔊 chore(highlight/index.tsx): add console log for selection in Highlight component

🔧 refactor(highlight/index.tsx): remove unnecessary spread operator in Word component

---

src/stories/highlight/index.stories.tsx
src/stories/highlight/index.tsx

🐛 fix(highlight/index.tsx): fix passing observation prop to StyledWord component

🔨 refactor(highlight/index.tsx): improve logic to find closest observation to word

---

src/stories/player/parts/bookmark.tsx
src/stories/player/parts/controls.tsx

🚀 feat(controls.tsx): add CurrentTimeMarker component with dynamic left position

🎨 style(bookmark.tsx): add z-index property to hovered bookmark for better layering

---

src/stories/highlight/demo-parts/transcript-diarization.tsx
src/stories/highlight/index.tsx

This pull request includes improvements to the styling and functionality of the transcript diarization feature in the highlight component. The changes include:
- Improved styling for the transcript diarization feature
- Added functionality to handle selection of parts in the transcript
- Extracted text from the selection, cleaning unselectable items
- Updated the handling of observations containing words
These changes enhance the user experience and make the transcript diarization feature more robust and user-friendly.

"Improve styling and functionality for transcript diarization in highlight component"

---

src/stories/player/parts/cutterButton.tsx

🚀 feat(cutterButton.tsx): add styled component for Cutter button to prevent

---

src/stories/highlight/CreateObservationButton.tsx
src/stories/highlight/_types.tsx
src/stories/highlight/index.stories.tsx
src/stories/highlight/index.tsx

🔧 chore(highlight): refactor Highlight component to handle selection button click

🚀 feat(highlight): add CreateObservationButton component

---

src/stories/player/_types.tsx
src/stories/player/index.stories.tsx
src/stories/player/index.tsx
src/stories/player/parts/container.tsx
src/stories/player/parts/controls.tsx

🔧 fix(player): update Container and ControlsWrapper styles based on showControls prop

🚀 feat(player): add showControls prop to PlayerArgs and WrapperProps

---

src/stories/player/parts/controls.tsx
src/stories/player/parts/floatingControls.tsx

visibility and layout consistency

🩹 fix(controls.tsx, floatingControls.tsx): adjust height to 80px for better

---

src/stories/player/parts/CutStart.tsx
src/stories/player/parts/controls.tsx

✨ feat(player): add CutStart component to show start point when cutting video

---

src/stories/player/index.tsx
src/stories/player/parts/container.tsx
src/stories/player/parts/floatingControls.tsx

🔧 refactor(player): update Container styles based on showControls prop
🔧 refactor(player): update FloatingContainer styles based on showControls prop

🔧 refactor(player): add showControls prop to FloatingControls component

---

src/stories/player/index.stories.tsx
src/stories/player/index.tsx

This pull request refactors the Player component to use PlayerProvider for better context management. The Player component now uses PlayerProvider.Core to render the video player and handles the video playback and controls. This change improves the organization and maintainability of the code.

"Refactor Player component to use PlayerProvider for better context management"

---

.github/workflows/release.yml

This pull request includes several commits that refactor the authentication logic in the codebase. The changes aim to improve the security and efficiency of the authentication process.

Fix authentication logic

---

vite.config.mts

ci: Remove chunk split

---

src/stories/accordion-new/AccordionHeader.tsx

Adjust the alignment of the AccordionHeader component to enhance the overall layout. This change improves visual consistency and user experience.

Fix AccordionHeader alignment for improved layout

---

src/stories/cards/template-card/index.tsx

for improved template status display

feat: add Meta component to TemplateCard

---

src/stories/editor/floatingMenu.tsx

https://github.com/ueberdosis/tiptap/issues/3784

fix: Prevent error on removechild fro bubblemenu when toggling editable state

---

src/stories/buttons/button/index.stories.tsx
src/stories/theme/components.ts

Implement handling for the disabled state in the button component, ensuring that styles and interactions are appropriately adjusted when the button is disabled. This enhances user experience by preventing interactions when the button should not be active.

Add disabled state handling in button component
